# Generated by Django 3.2.11 on 2022-01-13 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmpltappp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pic1')),
                ('name', models.CharField(max_length=200)),
                ('des1', models.TextField()),
            ],
        ),
    ]
